const KEY='hr-saudi-employees-v3';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const write=(x:any[])=>localStorage.setItem(KEY,JSON.stringify(x));
const esc=(s:any)=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'} as any)[m]);
function download(name:string,text:string,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function mount(){if(document.querySelector('[data-hr-enhancements]'))return;const root=document.querySelector('main');if(!root)return;const box=document.createElement('div');box.dataset.hrEnhancements='1';box.className='hr-enhancements';box.innerHTML='<button class="secondary" data-action="backup">نسخة احتياطية</button><button class="secondary" data-action="restore">استعادة نسخة</button><input data-restore-file type="file" accept=".json" hidden>';root.prepend(box);box.querySelector('[data-action="backup"]')?.addEventListener('click',()=>download('HR-Saudi-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({employees:read(),settings:localStorage.getItem('hr-saudi-settings-v1'),forms:localStorage.getItem('hr-saudi-forms-v1')},null,2)));box.querySelector('[data-action="restore"]')?.addEventListener('click',()=>box.querySelector<HTMLInputElement>('[data-restore-file]')?.click());box.querySelector<HTMLInputElement>('[data-restore-file]')?.addEventListener('change',async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(Array.isArray(d.employees))write(d.employees);if(typeof d.settings==='string')localStorage.setItem('hr-saudi-settings-v1',d.settings);if(typeof d.forms==='string')localStorage.setItem('hr-saudi-forms-v1',d.forms);location.reload()}catch{alert('ملف النسخة الاحتياطية غير صالح')}});}
function enhanceEmployees(){const tables=[...document.querySelectorAll('table')];const table=tables.find(t=>t.textContent?.includes('سجل الموظفين'));if(!table||table.dataset.enhanced)return;table.dataset.enhanced='1';const head=table.querySelector('thead tr');if(head){const th=document.createElement('th');th.textContent='إجراءات';head.appendChild(th)}table.querySelectorAll('tbody tr').forEach(row=>{const cells=row.querySelectorAll('td');const id=(cells[0]?.textContent||'').match(/#([^\s]+)/)?.[1];const action=document.createElement('td');action.innerHTML='<button class="table-action edit">تعديل</button>';action.querySelector('button')?.addEventListener('click',e=>{e.stopPropagation();openEditor(id||'')});row.appendChild(action)});}
function openEditor(id:string){const employees=read();const emp=employees.find((x:any)=>String(x.id)===String(id));if(!emp)return;const fields=[['name','اسم الموظف'],['job','المسمى الوظيفي'],['dept','القسم'],['nationality','الجنسية'],['identity','الهوية/الإقامة'],['phone','الجوال'],['status','الحالة'],['joiningDate','تاريخ الالتحاق'],['iqama','انتهاء الإقامة'],['passport','انتهاء الجواز'],['workPermit','انتهاء رخصة العمل'],['insurance','انتهاء التأمين'],['salary','الأساسي'],['housing','بدل السكن'],['transport','بدل النقل'],['gosiWage','أجر GOSI'],['bank','البنك'],['iban','IBAN']];const overlay=document.createElement('div');overlay.className='overlay';overlay.innerHTML='<div class="modal"><div class="modal-head"><div><h2>تعديل بيانات الموظف</h2><p>تحديث الملف الوظيفي وحفظه محلياً</p></div><button class="close">×</button></div><div class="form-grid">'+fields.map(([k,l])=>`<label>${l}<input data-k="${k}" value="${esc(emp[k])}"></label>`).join('')+'</div><div class="modal-actions"><button class="secondary cancel">إلغاء</button><button class="primary save">حفظ التعديلات</button></div></div>';document.body.appendChild(overlay);const close=()=>overlay.remove();overlay.querySelector('.close')?.addEventListener('click',close);overlay.querySelector('.cancel')?.addEventListener('click',close);overlay.querySelector('.save')?.addEventListener('click',()=>{overlay.querySelectorAll<HTMLInputElement>('[data-k]').forEach(i=>{const k=i.dataset.k!;emp[k]=['salary','housing','transport','gosiWage'].includes(k)?Number(i.value)||0:i.value});write(employees);location.reload()})}
function watch(){mount();if(document.body.textContent?.includes('سجل الموظفين'))enhanceEmployees()}
new MutationObserver(watch).observe(document.body,{childList:true,subtree:true});setTimeout(watch,300);setTimeout(watch,1000);