const EMP_KEY='hr-saudi-employees-v3', MOV_KEY='hr-saudi-movements-v1', AUDIT_KEY='hr-saudi-audit-v1';

type AnyRec=Record<string,any>;
const read=(k:string,f:any[]=[])=>{try{const v=JSON.parse(localStorage.getItem(k)||'');return Array.isArray(v)?v:f}catch{return f}};
const write=(k:string,v:any)=>localStorage.setItem(k,JSON.stringify(v));
const esc=(s:any)=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'} as AnyRec)[m]);
const money=(n:any)=>Number(n||0).toLocaleString('ar-SA')+' ر.س';
const log=(action:string,details:string,employeeId='')=>{const a=read(AUDIT_KEY);a.unshift({id:Date.now().toString(),at:new Date().toISOString(),action,details,employeeId});write(AUDIT_KEY,a.slice(0,500));};
function validate(e:AnyRec){const errors:string[]=[];if(!String(e.name||'').trim())errors.push('اسم الموظف مطلوب');if(!String(e.id||'').trim())errors.push('الرقم الوظيفي مطلوب');if(e.iban&&String(e.iban).replace(/\s/g,'').toUpperCase().startsWith('SA')&&String(e.iban).replace(/\s/g,'').length!==24)errors.push('رقم IBAN السعودي يجب أن يتكون من 24 خانة');return errors;}
function modal(html:string){const o=document.createElement('div');o.className='overlay';o.innerHTML=html;document.body.appendChild(o);return o;}
function employeeProfile(e:AnyRec){const movements=read(MOV_KEY).filter((m:any)=>String(m.employeeId)===String(e.id));const o=modal(`<div class="modal"><button class="close">×</button><div class="drawer-head" style="padding:0 0 18px"><div class="avatar lg">${esc(String(e.name||'?')[0])}</div><div><h2>${esc(e.name)}</h2><p>${esc(e.job||'')} — ${esc(e.dept||'')}</p></div></div><div class="facts" style="margin-top:20px"><div><label>الرقم الوظيفي</label><strong>${esc(e.id)}</strong></div><div><label>الجنسية</label><strong>${esc(e.nationality)}</strong></div><div><label>الهوية/الإقامة</label><strong>${esc(e.identity)}</strong></div><div><label>الجوال</label><strong>${esc(e.phone)}</strong></div><div><label>تاريخ الالتحاق</label><strong>${esc(e.joiningDate)}</strong></div><div><label>الحالة</label><strong>${esc(e.status)}</strong></div><div><label>البنك</label><strong>${esc(e.bank)}</strong></div><div><label>IBAN</label><strong>${esc(e.iban)}</strong></div></div><div class="drawer-section" style="padding:22px 0 0"><h3>الاستحقاقات</h3><div class="facts"><div><label>الأساسي</label><strong>${money(e.salary)}</strong></div><div><label>بدل السكن</label><strong>${money(e.housing)}</strong></div><div><label>بدل النقل</label><strong>${money(e.transport)}</strong></div><div><label>أجر GOSI</label><strong>${money(e.gosiWage)}</strong></div></div></div><div class="drawer-section" style="padding:22px 0 0"><h3>المستندات</h3><div class="facts"><div><label>الإقامة</label><strong>${esc(e.iqama||'غير مسجل')}</strong></div><div><label>الجواز</label><strong>${esc(e.passport||'غير مسجل')}</strong></div><div><label>رخصة العمل</label><strong>${esc(e.workPermit||'غير مسجل')}</strong></div><div><label>التأمين الطبي</label><strong>${esc(e.insurance||'غير مسجل')}</strong></div></div></div><div class="drawer-section" style="padding:22px 0 0"><h3>المسار الوظيفي (${movements.length})</h3>${movements.length?movements.map((m:any)=>`<div class="alert"><div class="alert-info"><b>${esc(m.type)}</b><span>${esc(m.date)} — ${esc(m.note||'')}</span></div><strong>${esc(m.from||'')} → ${esc(m.to||'')}</strong></div>`).join(''):'<div class="empty">لا توجد حركات مسجلة</div>'}</div></div>`);o.querySelector('.close')?.addEventListener('click',()=>o.remove());}
function movementForm(e:AnyRec){const o=modal(`<div class="modal"><button class="close">×</button><h2>إضافة حركة وظيفية</h2><div class="form-grid"><label>نوع الحركة<select data-k="type"><option>ترقية</option><option>نقل</option><option>تعديل راتب</option><option>تغيير المسمى الوظيفي</option><option>تغيير الإدارة</option></select></label><label>التاريخ<input data-k="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>القيمة الجديدة<input data-k="to" placeholder="المسمى / الإدارة / الراتب الجديد"></label><label>ملاحظة<input data-k="note"></label></div><div class="modal-actions"><button class="secondary cancel">إلغاء</button><button class="primary save">حفظ الحركة</button></div></div>`);const close=()=>o.remove();o.querySelector('.close')?.addEventListener('click',close);o.querySelector('.cancel')?.addEventListener('click',close);o.querySelector('.save')?.addEventListener('click',()=>{const v=(k:string)=>(o.querySelector(`[data-k="${k}"]`) as HTMLInputElement)?.value||'';const m={id:Date.now().toString(),employeeId:e.id,date:v('date'),type:v('type'),from:String(e.job||e.dept||e.salary||''),to:v('to'),note:v('note')};const all=read(MOV_KEY);all.unshift(m);write(MOV_KEY,all);log('حركة وظيفية',`${m.type}: ${m.to}`,e.id);close();alert('تم حفظ الحركة الوظيفية');});}
function mount(){if(document.querySelector('[data-hr-module]'))return;const root=document.querySelector('main');if(!root)return;const box=document.createElement('div');box.dataset.hrModule='1';box.className='hr-module-toolbar';box.innerHTML='<button class="secondary" data-profile>ملف موظف</button><button class="secondary" data-movement>حركة وظيفية</button><span class="hr-module-note">ملف وظيفي ومسار وظيفي محلي</span>';root.prepend(box);box.querySelector('[data-profile]')?.addEventListener('click',()=>{const e=read(EMP_KEY)[0];if(e)employeeProfile(e);else alert('لا توجد بيانات موظفين')});box.querySelector('[data-movement]')?.addEventListener('click',()=>{const e=read(EMP_KEY)[0];if(e)movementForm(e);else alert('لا توجد بيانات موظفين')});}
function enhanceRows(){const table=[...document.querySelectorAll('table')].find(t=>t.textContent?.includes('سجل الموظفين'));if(!table)return;table.querySelectorAll('tbody tr').forEach(row=>{if(row.querySelector('[data-profile-row]'))return;const c=row.querySelectorAll('td');const id=(c[0]?.textContent||'').match(/#([^\s]+)/)?.[1]||'';const e=read(EMP_KEY).find((x:any)=>String(x.id)===id);if(!e)return;const b=document.createElement('button');b.className='table-action';b.dataset.profileRow='1';b.textContent='ملف';b.addEventListener('click',x=>{x.stopPropagation();employeeProfile(e)});const td=document.createElement('td');td.appendChild(b);row.appendChild(td);});}
function checkData(){const emps=read(EMP_KEY);const invalid=emps.flatMap((e:any)=>validate(e).map(x=>({id:e.id,name:e.name,error:x})));if(invalid.length)log('فحص البيانات',`تم اكتشاف ${invalid.length} ملاحظة`);}
const observer=new MutationObserver(()=>{mount();enhanceRows()});observer.observe(document.body,{subtree:true,childList:true});setTimeout(()=>{mount();enhanceRows();checkData()},400);setTimeout(()=>{mount();enhanceRows()},1200);
